apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {app: postgres}
  name: postgres-pv-claim
  #namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: {storage: 10Gi}