apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: scality
  name: scality-pv-claim
  #namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi