apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: scality
  name: scality-pv-claim
  namespace: assisted-installer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi