apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: assisted-service-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Assisted Service description
  displayName: Assisted Service
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - label:
          app.kubernetes.io/component: deployment
          app.kubernetes.io/managed-by: olm
          app.kubernetes.io/part-of: assisted-service
          app.kubernetes.io/version: 0.0.1
          name: postgres
        name: postgres
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: postgres
          strategy:
            type: RollingUpdate
          template:
            metadata:
              labels:
                app.kubernetes.io/component: deployment
                app.kubernetes.io/managed-by: olm
                app.kubernetes.io/part-of: assisted-service
                app.kubernetes.io/version: 0.0.1
                name: postgres
            spec:
              containers:
              - env:
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef: {key: db.name, name: assisted-installer-rds}
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef: {key: db.user, name: assisted-installer-rds}
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef: {key: db.password, name: assisted-installer-rds}
                image: quay.io/ocpmetal/postgresql-12-centos7
                imagePullPolicy: IfNotPresent
                name: postgres
                ports:
                - {containerPort: 5432}
                resources:
                  limits: {cpu: 200m, memory: 500Mi}
                  requests: {cpu: 100m, memory: 400Mi}
                volumeMounts:
                - {mountPath: /var/lib/postgress, name: postgredb}
              volumes:
              - name: postgredb
                persistentVolumeClaim: {claimName: postgres-pv-claim}
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - assisted-service
  links:
  - name: Assisted Service Operator
    url: https://assisted-service-operator.domain
  maturity: alpha
  provider:
    name: PROVIDER_NAME
    url: URL
  version: 0.0.1
