apiVersion: v1
data:
  ADMIN_USERS: ercohen,lgamliel,mfilanov,ygoldber
  AGENT_DOCKER_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  API_VIP_CONNECTIVITY_CHECK_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  BASE_DNS_DOMAINS: ''
  CONNECTIVITY_CHECK_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  CONTROLLER_IMAGE: quay.io/ocpmetal/assisted-installer-controller:latest
  CREATE_S3_BUCKET: 'true'
  DHCP_LEASE_ALLOCATOR_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  ENABLE_AUTH: 'False'
  FREE_ADDRESSES_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  INSTALLER_IMAGE: quay.io/ocpmetal/assisted-installer:latest
  INVENTORY_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  JWKS_URL: https://api.openshift.com/.well-known/jwks.json
  NAMESPACE: '{{ ansible_operator_meta.namespace }}'
  NTP_SYNCHRONIZER_IMAGE: quay.io/ocpmetal/assisted-installer-agent:latest
  OCM_BASE_URL: https://api-integration.6943.hive-integration.openshiftapps.com
  OPENSHIFT_VERSIONS: '{"4.6":{"release_image":"quay.io/openshift-release-dev/ocp-release:4.6.4-x86_64"},"4.7":{"release_image":"quay.io/openshift-release-dev/ocp-release@sha256:2419f9cd3ea9bd114764855653012e305ade2527210d332bfdd6dbdae538bd66"}}'
  PUBLIC_CONTAINER_REGISTRIES: quay.io
  SELF_VERSION: quay.io/ocpmetal/assisted-service:latest
  SERVICE_BASE_URL: http://assisted-service-assisted-installer.apps.ostest.test.metalkube.org
  SKIP_CERT_VERIFICATION: 'true'
  HW_VALIDATOR_MIN_DISK_SIZE_GIB: '20'
kind: ConfigMap
metadata:
  labels:
    app: assisted-service
  name: assisted-service-config
  namespace: '{{ ansible_operator_meta.namespace }}'