apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-service
  name: assisted-service
  #namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  ports:
    - name: assisted-service
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: assisted-service
  type: LoadBalancer
status:
  loadBalancer: {}