apiVersion: v1
kind: Service
metadata:
  labels: {app: postgres}
  name: postgres
  #namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  ports:
  - {port: 5432}
  selector: {app: postgres}
  type: LoadBalancer
status:
  loadBalancer: {}