
apiVersion: v1
kind: Secret
metadata:
  labels: {app: postgres}
  name: assisted-installer-rds
  #namespace: '{{ ansible_operator_meta.namespace }}'
stringData: {db.host: postgres, db.name: installer, db.password: admin, db.port: '5432',
  db.user: admin}
type: Opaque