apiVersion: v1
kind: Service
metadata:
  labels:
    app: scality
  name: cloudserver-front
  namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: scality
status:
  loadBalancer: {}