apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: assisted-service-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AssistedService is the Schema for the assistedservices API
      displayName: Assisted Service
      kind: AssistedService
      name: assistedservices.assistedservice.openshift.io.openshift.io
      version: v1alpha1
  description: Assisted Service description
  displayName: Assisted Service
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - assisted-service
  links:
  - name: Assisted Service Operator
    url: https://assisted-service-operator.domain
  maturity: alpha
  provider:
    name: PROVIDER_NAME
    url: URL
  version: 0.0.0
